apiVersion: kubefledged.io/v1alpha2
kind: ImageCache
metadata:
  name: gdc-local-cache
  namespace: kube-fledged
  labels:
    app: kubefledged
    component: imagecache
spec:
  cacheSpec:
  - images:
    - gcr.io/cloud-alchemists-sandbox/kube-fledged/kubefledged-webhook-server:latest
    - gcr.io/cloud-alchemists-sandbox/kube-fledged/kubefledged-controller:latest
    - gcr.io/cloud-alchemists-sandbox/kube-fledged/kubefledged-cri-client:latest
    - gcr.io/cloud-alchemists-sandbox/kube-fledged/kubefledged-operator:latest
    - gcr.io/cloud-alchemists-sandbox/kube-fledged/busybox:1.35.0
  # imagePullSecrets:
  # - name: image-pull-secret
