apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefledged-controller
  namespace: kube-fledged
  labels:
    app: kubefledged
    component: kubefledged-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      kubefledged: kubefledged-controller
  template:
    metadata:
      labels:
        kubefledged: kubefledged-controller
        app: kubefledged
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/cloud-alchemists-sandbox/kube-fledged-test/kubefledged-controller:latest
        command: ["/opt/bin/kubefledged-controller"]
        args:
        - "--stderrthreshold=INFO"
        - "--image-pull-deadline-duration=5m"
        - "--image-cache-refresh-frequency=15m"
        - "--image-pull-policy=IfNotPresent"
        imagePullPolicy: Always
        name: controller
        env:
        - name: KUBEFLEDGED_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBEFLEDGED_CRI_CLIENT_IMAGE
          value: "us-central1-docker.pkg.dev/cloud-alchemists-sandbox/kube-fledged-test/kubefledged-cri-client:latest"
        - name: BUSYBOX_IMAGE
          value: "us-central1-docker.pkg.dev/cloud-alchemists-sandbox/kube-fledged-test/busybox:1.35.0"
      serviceAccountName: kubefledged-controller
      imagePullSecrets:
      - name: artifact-registry
